#
# Module manifest for module 'OSDCloud'
#
# Generated by: David Segura
# Generated on: 2026-04-22
#

@{
    # --- Identity ---
    RootModule        = 'OSDCloud.psm1'
    ModuleVersion     = '26.8.10.1'
    CompatiblePSEditions = @('Core','Desktop')
    GUID              = '2fbd5c65-79c7-4561-9a2e-c4a4eebc89c7'

    # --- Authoring ---
    Author            = 'David Segura'
    CompanyName       = 'Recast Software'
    Copyright         = '(c) 2026 Recast Software. All rights reserved.'
    Description          = @'
PowerShell module for OSDCloud v2 deployment automation and WinPE Startup from recastsoftware.com.
Includes operating system, driver pack, and device provisioning workflows.
'@

    # --- Requirements ---
    PowerShellVersion    = '5.1'

    # --- Exports ---
    FunctionsToExport = @(
        # WinOS
        'Deploy-OSDCloud',
        'Get-OSDCloudModulePath',
        'Get-OSDCloudModuleVersion',
        'Show-OSDCloudDeviceInfo',
        'Start-OSDCloudExplorer',
        # WinPE
        'Invoke-WinPEStartup',
        'Invoke-WinPEStartupManager',
        'Show-WinPEStartupDeviceErrors',
        'Show-WinPEStartupDevices',
        'Show-WinPEStartupIpconfig',
        'Show-WinPEStartupWifi',
        'Update-WinPEStartupModule'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @(
        'Invoke-OSDCloudPEStartup',
        'Invoke-OSDCloudWifi',
        'OSDCloudExplorer',
        'Show-PEStartupDeviceInfo',
        'Show-PEStartupHardware',
        'Show-PEStartupErrors',
        'Show-PEStartupIpconfig',
        'Show-PEStartupWifi',
        'Use-PEStartupUpdateModule'
    )

    # --- Discovery ---
    PrivateData = @{
        PSData = @{
            Tags = @('OSDeploy','OSD','OSDCloud','OSDWorkspace','Recast')
            LicenseUri = 'https://github.com/OSDeploy/OSDCloud/blob/main/LICENSE'
            ProjectUri = 'https://github.com/OSDeploy/OSDCloud'
        }
    }
}
