#
# Module manifest for module 'OSDCloud'
#
# Generated by: David Segura
#

@{
    # --- Identity ---
    RootModule           = 'OSDCloud.psm1'
    ModuleVersion        = '26.10.9.1'
    CompatiblePSEditions = @('Core', 'Desktop')
    GUID                 = '2fbd5c65-79c7-4561-9a2e-c4a4eebc89c7'

    # --- Authoring ---
    Author               = 'David Segura'
    CompanyName          = 'Recast Software'
    Copyright            = '(c) 2026 Recast Software. All rights reserved.'
    Description          = @'
Recast OSDCloud PowerShell Module.
PowerShell module for OSDCloud v2 deployment automation and WinpeStartup from recastsoftware.com.
Includes operating system, driver pack, and device provisioning workflows.
Windows 11 26H2 GA Release
'@

    # --- Requirements ---
    PowerShellVersion    = '5.1'

    # --- Exports ---
    FunctionsToExport = @(
        # WinOS
        'Deploy-OSDCloud',
        'Get-OSDCloudModulePath',
        'Get-OSDCloudModuleVersion',
        'Show-OSDCloudDeviceInfo',
        'Start-OSDCloudExplorer',
        # WinPE
        'Invoke-WinpeStartup',
        'Invoke-WinpeStartupManager',
        'Show-WinpeStartupDeviceErrors',
        'Show-WinpeStartupDevices',
        'Show-WinpeStartupIpconfig',
        'Show-WinpeStartupWifi',
        'Update-WinpeStartupModule'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @(
        'Invoke-OSDCloudPEStartup',
        'Invoke-OSDCloudWifi',
        'OSDCloudExplorer',
        'Show-PEStartupDeviceInfo',
        'Show-PEStartupHardware',
        'Show-PEStartupErrors',
        'Show-PEStartupIpconfig',
        'Show-PEStartupWifi',
        'Use-PEStartupUpdateModule'
    )

    # --- Discovery ---
    PrivateData = @{
        PSData = @{
            Tags       = @('OSD', 'OSDeploy', 'OSDCloud', 'Recast', 'RecastSoftware')
            ProjectUri = 'https://github.com/RecastSoftware/RecastOSDCloud'
            LicenseUri = 'https://www.gnu.org/licenses/gpl-3.0.html'
        }
    }
}
